import streamlit as st
import pandas as pd
import numpy as np
import joblib

# Page configuration
st.set_page_config(
    page_title="Statin Non Adherence Risk Tool",
    page_icon="🫀",
    layout="centered"
)

# Header
st.title("🫀 Statin Non Adherence Risk Tool")
st.markdown("**Developed by Felicita Adeleke**")
st.markdown("Health Analytics Portfolio Project | 2026")

st.divider()

# Clinical disclaimer
st.info(
    "This tool is designed to support clinical prioritisation "
    "and should not replace professional clinical judgement. "
    "Risk scores are based on population level patterns from "
    "Czech prescription data 2017 to 2020."
)

st.divider()

# Load model
model = joblib.load("balanced_logistic_model.pkl")

# Input section
st.subheader("Patient Characteristics")

col1, col2 = st.columns(2)

with col1:
    gender = st.selectbox("Gender", ["Females", "Males"])
    age_group = st.selectbox(
        "Age Group",
        ["30-44", "45-59", "60-74", "75-89", "90+"]
    )
    incident = st.selectbox(
        "New Patient?",
        [0, 1],
        format_func=lambda x: "Yes - New Patient" if x == 1 else "No - Existing Patient"
    )

with col2:
    order = st.number_input(
        "Prescription Order Number",
        min_value=1,
        max_value=42,
        value=1
    )
    statin_intensity = st.selectbox(
        "Statin Intensity",
        ["high", "low/moderate"]
    )

st.divider()

# Build input dataframe
input_data = pd.DataFrame({
    "incident": [incident],
    "order": [order],
    "gender_Males": [1 if gender == "Males" else 0],
    "age_group_30-44": [1 if age_group == "30-44" else 0],
    "age_group_45-59": [1 if age_group == "45-59" else 0],
    "age_group_60-74": [1 if age_group == "60-74" else 0],
    "age_group_75-89": [1 if age_group == "75-89" else 0],
    "age_group_90+": [1 if age_group == "90+" else 0],
    "statin_intensity_low/moderate": [
        1 if statin_intensity == "low/moderate" else 0
    ]
})

# Predict button
if st.button("Calculate Risk Score", type="primary"):

    risk = model.predict_proba(input_data)[0][1]

    if risk < 0.33:
        band = "Low"
    elif risk < 0.66:
        band = "Medium"
    else:
        band = "High"

    st.divider()
    st.subheader("Predicted Risk Output")

    col1, col2 = st.columns(2)

    with col1:
        st.metric(
            label="Risk Score",
            value=f"{risk:.2f}"
        )

    with col2:
        st.metric(
            label="Risk Band",
            value=band
        )

    if band == "Low":
        st.success("LOW RISK: Standard monitoring is appropriate.")
        st.write(
            "This patient has a low predicted probability of "
            "becoming non adherent based on their characteristics. "
            "Continue standard prescription review at next appointment."
        )
    elif band == "Medium":
        st.warning("MEDIUM RISK: Consider proactive follow up.")
        st.write(
            "This patient has a moderate predicted probability of "
            "becoming non adherent. A brief adherence conversation "
            "at their next appointment is recommended."
        )
    else:
        st.error("HIGH RISK: Proactive outreach recommended.")
        st.write(
            "This patient has a high predicted probability of "
            "becoming non adherent. Direct outreach and targeted "
            "adherence support is recommended before their next "
            "prescription is due."
        )

    st.divider()
    st.caption(
        "Risk scores are generated by a balanced logistic regression "
        "model trained on 1.39 million prescription records. "
        "Developed by Felicita Adeleke | Health Analytics Portfolio Project 2026."
    )